### ISSUE TITLE
Contract end date is shown as today's date

### ISSUE THREAD

**Issue by ajaysan91** [rjhalvorson/cancelAndReplace#1]
Hello, 

First of all, thanks a lot for building such an amazing solution.

We found a small issue after installing the CancelAndReplace in our org that the Contract End date on activeContract LWC is actually showing today's date and on further checking i see that the code used is the contract.terminationDate which is set as Date.today() in ContractService Apex class.
Instead of using contract.terminationDate under end date can we use contract.endDate so that we can show the correct end date details on the Contract listing.

```
<td data-label={label.endDate}>
     <div class="active-contracts-table-header">{label.endDate}</div>
     <div class="slds-truncate" title={contract.**endDate**}>{contract.**endDate**}</div>
</td>
```

Regards,
Ajay

**Comment by dgunaseelan** [comment]
@ajaysan91 Thank you for reporting the issue. It has now been resolved.
