### ISSUE TITLE
Test Classes need to be updated for PSLs

### ISSUE THREAD

**Issue by bgaldino** [rjhalvorson/cancelAndReplace#2]
Deploy scripts fail when deploying to an org with CPQ packages that require PSLs.  I have updated the TestUserFactory class to obtain and assign CPQ PSLs during test runs.

**Comment by komalnayyar** [comment]
Hi, I tried customizing this package and I see the code coverage is not upto the mark for the classes that I did not change directly or indirectly. Do you have idea on this? Am I missing any step?
