### ISSUE TITLE
Can you please make cancel and replace documentaion public?

### ISSUE THREAD

**Issue by gvpatel** [rjhalvorson/cancelAndReplace#6]
Can you please make documentation public?

Salesforce CPQ - Cancel and Replace

Documentation Link: https://salesforce.quip.com/KXBRArvmUQcG

**Comment by rjhalvorson** [comment]
@gvpatel - the documentation is public. (I am able to access it via chrome incognito). Perhaps something on your side?

**Comment by gvpatel** [comment]
Hi @rjhalvorson  It working fine in chrome incognito mode. thanks :)

**Comment by ehsky** [comment]
@rjhalvorson could you make the documentation public again? ☺️ 

Tested in 2 browser in incognito mode and gets redirected to okta auth portal for Salesforce.

**Comment by VedikaEdulachanti** [comment]
Could you please make documentation public https://salesforce.quip.com/KXBRArvmUQcG. I have tried to access in incognito but still asking credentials?

**Comment by russlogik** [comment]
@VedikaEdulachanti @ehsky - unfortunately I am no longer at Salesforce and do not have access to the document anymore.
