### ISSUE TITLE
Documentation Link Unavailable

### ISSUE THREAD

**Issue by SmithStyleDev** [rjhalvorson/cancelAndReplace#9]
The linked documentation is no longer available. I've asked Salesforce Support and they are unable to access or provide an updated link. Are you able to provide an updated link to documentation here by chance?

The link you have posted on main page (that no longer works):
Documentation Link: https://salesforce.quip.com/KXBRArvmUQcG

**Comment by russlogik** [comment]
@SmithStyleDev - unfortunately I am no longer with the company and I am unable to find someone to update the link.

**Comment by rjhalvorson** [comment]
Hi @SmithStyleDev - unfortunately I am no longer with the company and am unable to find someone to update a link.
